

// utils/allExclusives.js

function uniq(arr) {
  return [...new Set(arr.filter(Boolean))];
}

function normalizeId(value) {
  return String(value || "").toLowerCase().replace(/\s+/g, "").trim();
}

const ALL_EXCLUSIVE_ITEMS = {
  skins: uniq([
    "Character_StrayManta",
    "Character_UnbrokenTrash",
    "Character_WaltzScout",
    "Character_OasisCheck",
    "Character_CoolSuitable",
    "Character_AsterOrder",
    "Character_CrownOrder",
    "Character_SummerUnsuitable",
    "Character_SmoothSuede",
    "Character_ToyMonkeyOrca",
    "Character_SleekBiker",
    "Character_KernelRuse",
    "Character_FitVapor",
    "Character_TubaGummi",
    "Character_SnowNinjaDark",
    "Character_VitalInventorBlock",
    "Character_ShiitakeShaolin_Rouge",
    "Character_Scribble",
    "Character_CometWinter",
    "Character_BlueJet",
    "Character_MasterKeyOrder",
    "CID_713_Athena_Commando_M_MaskedWarriorSpring",
    "CID_A_421_Athena_Commando_F_BlizzardBomber",
    "CID_A_297_Athena_Commando_F_Network",
    "CID_850_Athena_Commando_F_SkullBriteCube",
    "CID_A_096_Athena_Commando_F_TaxiUpgradedMulticolor",
    "CID_660_Athena_Commando_F_BandageNinjaBlue",
    "CID_926_Athena_Commando_F_StreetFashionDiamond",
    "CID_783_Athena_Commando_M_AquaJacket",
    "CID_757_Athena_Commando_F_WildCat",
    "CID_851_Athena_Commando_M_Bittenhead",
    "CID_711_Athena_Commando_M_LongShorts",
    "CID_657_Athena_Commando_F_TechOpsBlue",
    "CID_479_Athena_Commando_F_Davinci",
    "CID_516_Athena_Commando_M_BlackWidowRogue",
    "CID_441_Athena_Commando_F_CyberScavengerBlue",
    "CID_434_Athena_Commando_F_StealthHonor",
    "CID_371_Athena_Commando_M_SpeedyMidnight",
    "CID_386_Athena_Commando_M_StreetOpsStealth",
    "CID_360_Athena_Commando_M_TechOpsBlue",
    "CID_313_Athena_Commando_M_KpopFashion",
    "CID_296_Athena_Commando_M_Math",
    "CID_342_Athena_Commando_M_StreetRacerMetallic",
    "CID_183_Athena_Commando_M_ModernMilitaryRed",
    "CID_174_Athena_Commando_F_CarbideWhite",
    "CID_175_Athena_Commando_M_Celestial",
    "CID_095_Athena_Commando_M_Founder",
    "CID_096_Athena_Commando_F_Founder",
    "CID_138_Athena_Commando_M_PSBurnout",
    "CID_114_Athena_Commando_F_TacticalWoodland",
    "CID_113_Athena_Commando_M_BlueAce",
    "CID_089_Athena_Commando_M_RetroGrey",
    "CID_085_Athena_Commando_M_Twitch",
    "CID_052_Athena_Commando_F_PSBlue",
    "CID_619_Athena_Commando_F_TechLlama",
    "CID_954_Athena_Commando_F_Football20Referee_C_NAQ0G",
    "CID_948_Athena_Commando_M_Football20Referee_B_QPXTH",
  ]),

  backblings: uniq([
    "Backpack_StrayManta",
    "Backpack_NitroNova",
    "Backpack_ToadCycle",
    "Backpack_RainbowHatPink",
    "Backpack_JackColby",
    "Backpack_FNCSShield_S38",
    "Backpack_HangedGrit",
    "Backpack_AsterOrder",
    "Backpack_AsterOrder_Mic",
    "Backpack_AsterOrder_Guitar",
    "Backpack_CrownOrder",
    "Backpack_ToyMonkeyOrca",
    "Backpack_FNCSShieldS36",
    "Backpack_SmoothSuede",
    "Backpack_BaldAble",
    "Backpack_FNCSShield_S34",
    "Backpack_FitVapor",
    "Backpack_FNCSShield_S33",
    "Backpack_SnowNinjaDark",
    "Backpack_FNCSShield_S32",
    "Backpack_AgentAceHeart",
    "Backpack_Dango",
    "Backpack_ButterVehicle",
    "Backpack_FNCSShield_S30",
    "Backpack_GummiBarren",
    "Backpack_FNCSShield_S29",
    "Backpack_TiltedParrotFrog_Custard",
    "Backpack_SnowSoldierFashion",
    "Backpack_VitalInventorBlock",
    "Backpack_CyberRunnerGolden",
    "Backpack_CraneGame",
    "Backpack_FNCSShield26",
    "Backpack_ShiitakeShaolin_Rouge",
    "Backpack_FNCS25",
    "Backpack_SurfAttackVibe",
    "Backpack_FolkEvening",
    "Backpack_Scribble",
    "Backpack_FNCS24",
    "Backpack_FNCS23",
    "Backpack_BlueJet",
    "Backpack_Radish",
    "Backpack_FNCS22",
    "BID_834_MaskedWarriorSpring",
    "BID_A_019_BlizzardBomberFemale",
    "BID_943_LlamaLeague",
    "BID_604_SkullBritecube",
    "BID_860_BigBucksRaceCar_5T4NY",
    "BID_857_BigBucksCat_XTZ62",
    "BID_862_BigBucksBattleship_1JA5G",
    "BID_855_BigBucksDog_S1Y8P",
    "BID_859_BigBucksPenguin_6NSWA",
    "BID_858_BigBucksRex_K3JSQ",
    "BID_861_BigBucksTopHat_J5LQQ",
    "BID_856_BigBucksDuck_0751N",
    "BID_766_TacticalWoodlandBlue",
    "BID_452_BandageNinjaBlue",
    "BID_644_StreetFashionDiamond",
    "BID_521_WildCat",
    "BID_542_Foam",
    "BID_469_Wings",
    "BID_482_LongShorts",
    "BID_448_TechOpsBlueFemale",
    "BID_346_BlackWidowRogue",
    "BID_288_CyberScavengerFemaleBlue",
    "BID_234_SpeedyMidnight",
    "BID_249_StreetOpsStealth",
    "BID_224_TechOpsBlue",
    "BID_169_MathMale",
    "BID_138_Celestial",
    "BID_114_ModernMilitaryRed",
    "BID_033_FounderFemale",
    "BID_032_FounderMale",
    "BID_055_PSBurnout",
    "BID_049_TacticalWoodland",
    "BID_029_RetroGrey",
    "BID_415_TechLlama",
  ]),

  pickaxes: uniq([
    "Pickaxe_NitroNova",
    "Pickaxe_StrayManta",
    "Pickaxe_JackColby",
    "Pickaxe_AsterOrder",
    "Pickaxe_AsterOrder_Mic",
    "Pickaxe_AsterOrder_Guitar",
    "Pickaxe_CrownOrder",
    "Pickaxe_FNCSChampion",
    "Pickaxe_SmoothSuede",
    "Pickaxe_FitVapor",
    "Pickaxe_MinionBlossom",
    "Pickaxe_SnowNinjaDark",
    "Pickaxe_CyberFuReboot32",
    "Pickaxe_BandageNinjaHeart",
    "Pickaxe_PopBucket",
    "Pickaxe_PinkTrooperBarren",
    "Pickaxe_Paper",
    "Pickaxe_AgentRoguePoison",
    "Pickaxe_SpookyNeonBlue",
    "Pickaxe_SkullPunkBlade",
    "Pickaxe_WingedMedieval",
    "Pickaxe_SpookyNeonRed",
    "Pickaxe_ShiitakeShaolin_Rouge",
    "Pickaxe_PunkDevilVibe",
    "Pickaxe_AccumulateRetro",
    "Pickaxe_BlueJet",
    "Pickaxe_MasterKeyOrderMale",
    "Pickaxe_ID_802_EternalVanguardFemale",
    "Pickaxe_ID_654_MaskedWarriorSpringMale1H",
    "Pickaxe_ID_759_JetSkiCrystalFemale1H",
    "Pickaxe_SnowSoldierFashion",
    "Pickaxe_ID_757_BlizzardBomberFemale1H",
    "Pickaxe_ID_461_SkullBriteCube",
    "Pickaxe_ID_717_NetworkFemale",
    "Pickaxe_ID_602_TaxiUpgradedMulticolorFemal",
    "Pickaxe_ID_398_WildCatFemale",
    "Pickaxe_ID_195_SpaceBunny",
    "Pickaxe_ID_560_TacticalWoodlandBlueMale",
    "Pickaxe_ID_338_BandageNinjaBlue1H",
    "Pickaxe_ID_400_AquaJacketMale",
    "Pickaxe_ID_464_LongShortsMale",
    "Pickaxe_ID_447_SpaceWandererMale",
    "Pickaxe_ID_294_CandyCane",
    "Pickaxe_ID_256_TechOpsBlue",
    "Pickaxe_ID_178_SpeedyMidnight",
    "Pickaxe_ID_189_StreetOpsStealth",
    "Pickaxe_ID_116_Celestial",
    "Pickaxe_ID_099_ModernMilitaryRed",
    "Pickaxe_ID_077_CarbideWhite",
    "Pickaxe_ID_088_PSBurnout",
    "Pickaxe_ID_153_RoseLeader",
    "Pickaxe_ID_237_Warpaint",
    "Pickaxe_ID_044_TacticalUrbanHammer",
    "Pickaxe_ID_039_TacticalBlack",
  ]),

  gliders: uniq([
    "Glider_FlakeSled",
    "Glider_GoggleBud",
    "Glider_SnailAisle",
    "Glider_Baruim_Reboot32",
    "Glider_PlagueWaste",
    "Glider_JellyFishBarren",
    "Glider_TaxiUpgradedWhiteFemale",
    "Glider_SnowSoldierFashion",
    "Glider_WingedMedieval",
    "TaxiUpgradedMulticolourFemale",
    "Glider_ID_309_TacticalWoodlandBlue",
    "Glider_ID_211_WildCatBlue",
    "Glider_ID_210_GraffitiAssassinFemale",
    "Glider_ID_212_AquaJacketMale",
    "Glider_ID_217_LongshortsMale",
    "Glider_ID_196_CycloneMale",
    "Glider_ID_187_GalileoKayak_Q8THV",
    "Glider_ID_161_RoseLeader",
    "Glider_ID_150_TechOpsBlue",
    "Glider_ID_131_SpeedyMidnight",
    "Glider_ID_137_StreetOpsStealth",
    "Glider_ID_117_Warpaint",
    "Glider_ID_056_CarbideWhite",
    "Glider_ID_090_Celestial",
    "Glider_ID_075_ModerMilitaryRed",
    "Glider_ID_067_PSBurnout",
    "Glider_ID_018_Twitch",
    "Glider_ID_013_PSBlue",
    "FounderUmbrella",
    "FounderGlider",
  ]),

  emotes: uniq([
    "EID_HiccupPanic",
    "EID_WishingStar",
    "EID_EyeSpire",
    "EID_SwordSplit",
    "EID_Avian",
    "EID_Mic_SpinSlide",
    "EID_Drum_Pullups",
    "EID_Bass_KyleThrowBass",
    "EID_Mic_SlipTheMic",
    "EID_Potassium",
    "EID_Toasted",
    "EID_GroovingSparkle",
    "EID_Hoppin",
    "EID_MagicMan",
    "EID_PlayerEleven",
    "EID_Davinci",
    "EID_KPopDance03",
    "EID_BoogieDown",
    "EID_HipHop01",
  ]),

  sprays: uniq([
    "Spray_QuartzSqueak",
    "Spray_LanternFest26Cup",
    "Spray_PSCupBR",
    "Spray_Yonder_Drip",
    "Spray_FNCS_S39",
    "SPID_245_Valentines2021_2",
    "Spray_S38FNCSCommunityCup",
    "Spray_S38FNCSPlaystationCup",
    "Spray_S38FNCSBlitzCup",
    "Spray_PineTrim",
    "Spray_EssayView",
    "Spray_BRCup4",
    "Spray_FNCSGC1",
    "Spray_34PSCupZB",
    "Spray_FlavorStock",
    "Spray_RowdyDevilFNCS",
    "Spray_TimberStake2",
    "Spray_TimberStake",
    "Spray_TimberStake3",
    "Spray_KingsLeague",
    "Spray_KingsLeague2",
    "Spray_S35MSEE5",
    "Spray_S35MSEE4",
    "Spray_S35MSEE3",
    "Spray_S35MSEE2",
    "Spray_S35MSEE",
    "Spray_FNCSProW2",
    "Spray_FNCSProW1",
    "Spray_BRCup",
    "Spray_FNCSWaywardRebel2",
    "Spray_FNCSWaywardRebel",
    "Spray_LanternFest25",
    "Spray_TwilightSpot",
    "Spray_FNCSWildCard",
    "Spray_MallardVintageFNCS",
    "Spray_LivelyDominoZB",
    "Spray_FreeDive_Community",
    "Spray_CattleJar_Community",
    "Spray_FallChampionships2",
    "Spray_FallChampionships",
    "Spray_SparksElegantLily3",
    "SPID_450_Competitive_Catalyst",
    "SPID_451_Competitive_Fade",
    "SPID_449_Competitive_BurningWolf",
    "Spray_ReferAFriend",
    "Spray_CinderMax_Fireball",
    "Spray_RebootRalley",
    "Spray_Competitive_PeelyDrop",
    "Spray_Competitive_CTLDrop",
    "Spray_S24_FNCSDrops",
    "SPID_379_PostpartyReward",
    "Spray_S23_FNCS_Drops",
    "Spray_Honk",
    "Spray_FunBreak",
    "Spray_Invitational",
    "Spray_Showdown_Pi",
    "Spray_Showdown_Mae",
    "Spray_Showdown_Co",
    "Spray_PurpleFootballLlama",
    "SPID_440_Spectacle",
    "SPID_432_FNCSDrops",
    "SPID_435_ReferFriend",
    "SPID_368_LittleEggChick",
    "SPID_383_FNCSDrops",
    "SPID_402_Lyrical_Name",
    "SPID_382_UERaider",
    "SPID_381_Windwalker",
    "SPID_359_Dr_U39EK",
    "SPID_353_FNCS_Drops",
    "SPID_354_HelmetDrops",
    "SPID_347_ShowdownTomato",
    "SPID_349_ShowdownPanda",
    "SPID_348_ShowdownReaper",
    "SPID_328_GrasshopperHammer_5D0FN",
    "SPID_322_Grasshopper_83HQ3",
    "SPID_327_GrasshopperHeart_CP6MR",
    "SPID_310_CritterFrenzyJar",
    "SPID_308_CritterCuddleLlama",
    "SPID_319_FNCS18",
    "SPID_298_Console",
    "SPID_297_ReferAFriendTaxi",
    "SPID_289_RiftTourAccLink_X1FV9",
    "SPID_296_FNCS",
    "SPID_282_FNCS_AllStarsAlt2",
    "SPID_281_FNCS_AllStars",
    "SPID_280_Fest",
    "SPID_275_Soccer",
    "SPID_279_EasyLife",
    "SPID_261_Basketball_2021_MIAO3",
    "SPID_259_RebootAFriend",
    "SPID_260_S16_FNCS",
    "SPID_257_TempleCreative",
    "SPID_242_S15_FNCS",
    "SPID_229_S14_FNCS",
    "SPID_215_MeowsclesBox",
    "SPID_216_S13_FNCS",
    "SPID_217_TheBratHotdog",
    "SPID_206_EyeballOctopus",
    "SPID_204_S12_FNCS",
    "SPID_200_GoldMeowscles",
    "SPID_196_CarnavalA",
    "SPID_197_CarnavalB",
    "SPID_179_S11_FNCS",
    "SPID_174_Tiger",
    "SPID_172_Shaka",
    "SPID_171_Rose",
    "SPID_170_Quokka",
    "SPID_173_ThumbsUp",
    "SPID_169_Eucalyptus",
    "SPID_126_WorldCup",
    "SPID_066_Llamalaxy",
    "SPID_043_Flairspray",
    "SPID_130_GameJam2019",
    "SPID_065_DiscoBaller",
    "SPID_042_LlamaControllers",
    "SPID_023_E3",
    "SPID_041_GC2018",
  ]),

  wraps: uniq([
    "Wrap_Glare",
    "Wrap_StrongHibiscus",
    "Wrap_BunnyPurple_Festive",
    "Wrap_AsterOrder",
    "Wrap_RoomReader",
    "Wrap_HotWax",
    "Wrap_ChillyTime",
    "ChillyFabric",
    "Wrap_TotalFlock",
    "Wrap_SoapPocket",
    "Wrap_GarlicWhisk",
    "Wrap_BlackSwirlB",
    "Wrap_UnknownNetwork",
    "Wrap_Mitosis",
    "Wrap_LimeJacket",
    "Wrap_AlienMaze",
    "Wrap_DyedBurst",
    "Wrap_SnowNinjaDark",
    "Wrap_CyberFuBarium",
    "Wrap_TemporalOven",
    "Wrap_TaffyHeart",
    "Wrap_Gummybarren",
    "Wrap_PaperBlaze",
    "Wrap_AgentRogueGreen",
    "Wrap_SkullPunkBlade",
    "Wrap_WingedMedieval",
    "Wrap_ShiitakeShaolin_Rouge",
    "Wrap_PunkDevilVibe",
    "Wrap_464_PostParty",
    "Wrap_ClubSound",
    "Wrap_474_MasterKey",
    "Wrap_507_SummerVivid",
    "Wrap_498_Waves",
    "Wrap_497_MaskedWarriorSpring",
    "Wrap_459_MilitaryFashionCamo",
    "Wrap_SnowSoldierFashion",
    "Wrap_447_BlizzardBomber",
    "Wrap_355_TaxiUpgradedMulticolor",
    "Wrap_405_GreenGel",
    "Wrap_326_Flatline",
    "Wrap_333_StealthWoodland",
    "Wrap_301_CosmicPulse",
    "Wrap_299_Holo",
    "Wrap_303_GasCloud",
    "Wrap_293_Phantom",
    "Wrap_281_LongShorts",
    "Wrap_254_NeonBands",
    "Wrap_168_EyeballOctopus",
    "Wrap_223_Fryangles",
    "Wrap_121_TechOpsBlue",
    "Wrap_103_Yatter",
    "Wrap_016_CuddleTeam",
  ]),

  emoticons: uniq([
    "Emoticon_RampCanalFNCS",
    "Emoticon_Refrigerator2",
    "Emoticon_Refrigerator",
    "Emoticon_S39_RankedCup",
    "Emoticon_BoldDorm",
    "Emoticon_Vegetable",
    "Emoticon_PineTrim",
    "Emoticon_FNCSGC",
    "Emoticon_EggnogFaucet",
    "Emoticon_RowdyDevilFNCS",
    "Emoticon_TimberStake",
    "Emoticon_S35_MoleAcorn",
    "Emoji_S34_LanternFest25",
    "Emoji_S31_LivelyDominoZB2",
    "Emoji_S31_FallChampionship2",
    "Emoji_S31_FallChampionship",
    "Emoji_S31_SparksElegantLily3",
    "Emoji_S31_SparksElegantLily2",
    "Emoji_S21_Wavy_Komplex",
    "Emoji_S21_Wavy_Powerchord1",
    "Emoji_S29_GuineaPig",
    "Emoji_S21_Wavy_MechaCuddle",
    "Emoji_S21_Wavy_Powerchord2",
    "Emoji_S27_RebootRally",
    "Emoji_S26_FNCSDrops",
    "Emoji_S25_FNCSDrops",
    "Emoji_S19_IslandNomad",
    "Emoji_S24_FNCSDrops",
    "Emoji_S21_Wavy_Drift",
    "Emoji_S23_OceanBreeze_Smile",
    "Emoji_S20_GG_Gas",
    "Emoji_S23_RebootRally",
    "Emoji_S22_FunBreak",
    "Emoji_S22_Invitational",
    "Emoji_S22_Showdown_Pi",
    "Emoji_S22_Showdown_Mae",
    "Emoji_S22_Showdown_Co",
    "Emoji_S22_RebootRally_RenegadeRaider",
    "Emoji_S19_FNCS_AnimatedBeep",
    "Emoji_S20_GG_Cube",
    "Emoji_S19_FNCS_BusBounce",
    "Emoji_S21_FNCS",
    "Emoji_S21_CatDrop",
    "Emoji_S21_CritterDrop",
    "Emoji_S20_Teknique_Competitive",
    "Emoji_S23_SnowSoldierFashion",
    "Emoji_S19_BlizzardBomber",
    "Emoji_S18_DriftDash",
    "Emoji_S19_FNCS_Drops",
    "Emoji_S19_FootballDrops",
    "Emoji_S19_TouchdownDrops",
    "Emoji_S19_ShowdownTomato",
    "Emoji_S19_ShowdownPanda",
    "Emoji_S19_ShowdownReaper",
    "Emoji_S18_GrandRoyaleCompetition",
    "Emoji_S18_FNCS",
    "Emoji_S18_SadToonFishstick",
    "Emoji_S17_StreamElementsDJ",
    "Emoji_S17_StreamElementsPeely",
    "Emoji_S17_StreamElementsSlurpMonster",
    "Emoji_S17_StreamElementsRaptor",
    "Emoji_S17_FNCS",
    "Emoji_S17_Fest",
    "Emoji_S17_FNCS_AllStars",
    "Emoji_S17_Soccer",
    "Emoji_S16_Bicycle2",
    "Emoji_S16_FNCS",
    "Emoji_S15_PS_PlusPack_2021",
    "Emoji_S15_FNCS",
    "Emoji_S14_RebootAFriend",
    "Emoji_S14_FNCS",
    "Emoji_S14_PS_PlusPack_11",
    "Emoji_S14_Elastic_Umbrella",
    "Emoji_S14_Elastic_Taco",
    "Emoji_S14_Elastic_Butterfly",
    "Emoji_S14_Elastic_FishBone",
    "Emoji_S14_Elastic_PinkArrow",
    "Emoji_S14_Elastic_Bomb",
    "Emoji_S13_FNCS",
    "Emoji_S12_FNCS",
    "Emoji_TechOpsBlue",
    "Emoji_Pizza",
  ]),

  loadingScreens: uniq([
    "LoadingScreen_CactusCowboy",
    "LoadingScreen_SWKeyArt",
    "LoadingScreen_Chow",
    "LoadingScreen_TrumpetPromo",
    "LoadingScreen_S34Quest4",
    "LoadingScreen_S34Quest3",
    "LoadingScreen_34Quest2",
    "LoadingScreen_KelpLinenMagnesium",
    "LoadingScreen_StageCueSparks",
    "LoadingScreen_GoldCatSparks",
    "LoadingScreen_DenimEquipSparks",
    "LoadingScreen_GourdRiddance",
    "LoadingScreen_EcosystemKeyArt",
    "LoadingScreen_DurianKeyArt",
    "LoadingScreen_FNCSDrops26",
    "LSID_390_KittyWarrior",
    "LoadingScreen_S25_FNCSDrops",
    "LoadingScreen_S24_FNCSDrops",
    "LoadingScreen_S23_FNCS_Drops",
    "LoadingScreen_DowntimeMicrosite_Reward",
    "LoadingScreen_Invitational",
    "LoadingScreen_SCRN_Fortnitemares_2022",
    "LoadingScreen_Spectacle",
    "LSID_465_MaskedDancer",
    "LSID_438_Armadillo",
    "LSID_427_FNCSDrops",
    "LSID_422_TacticalBR_Reward1",
    "LSID_424_NoPermit",
    "LSID_401_FNCS_Drops",
    "LSID_353_ReferaFriendTaxi",
    "LSID_359_Giggle_6OHH8",
    "LSID_354_FNCS18",
    "LSID_335_WastelandWarrior",
    "LSID_331_FNCS",
    "LSID_291_S16_FNCS",
    "LSID_271_FNCS_S15_ChampAxe",
    "LSID_257_FNCS_CuddleTeam",
  ]),

  kicks: uniq([
    "Shoes_BlossomFoot",
  ]),

  musicPacks: uniq([
    "MusicPack_199_DelMarDefault",
    "MusicPack_198_JunoDefault",
    "MusicPack_196_S28DefaultTrack",
    "MusicPack_192_Rufus",
    "MusicPack_156_Radish_Event",
    "MusicPack_162_S23Default",
    "MusicPack_133_Armadillo",
    "MusicPack_121_CH3_DefaultMusic",
    "MusicPack_108_Paperbag_R2R4P",
    "MusicPack_073_RL2PromoTrack",
    "MusicPack_063_KeydUp",
  ]),

  rocketRacing: uniq([
    "Wheel_RL190",
    "ID_Booster_PlasmaEnergyBW",
  ]),

  festival: uniq([
    "Sparks_AsterOrder_Guitar",
    "Sparks_AsterOrder_Mic",
    "Sparks_Drum_FrogCabinet",
    "SID_Placeholder_58",
    "SID_Placeholder_35",
  ]),

  banners: uniq([
    "Banner_TimberStake",
    "BRS31_CattleJar_Community",
    "BRS31_FreeDive_Community",
    "BRS23_FNCS_Drops",
    "S11FNCS",
    "BRS22_Showdown_Zet",
    "BRS22_Showdown_Pi",
    "BRS22_Showdown_Mae",
    "BRS22_Showdown_Co",
    "BRS23_SnowSoldierFashion",
    "BRS19_BlizzardBomber",
    "BRS19_ShowdownPanda",
    "BRS19_ShowdownReaper",
    "BRS19_ShowdownTomato",
    "BRS17_ReferAFriendTaxi",
    "BRS16_Basketball_2021_G89SL",
    "BRS15_PSPlusPack2021",
    "BRS14_PSPlusPack11",
    "BRS12_BrazilDrum",
    "BRS10BlackMondayTeaser",
    "NewsletterBanner",
    "OtherBanner51",
    "OT9Banner",
    "OT8Banner",
    "OT7Banner",
    "OT6Banner",
    "OT5Banner",
    "OT4Banner",
    "OT3Banner",
    "OT2Banner",
    "OT1Banner",
    "OT11Banner",
    "OT10Banner",
  ]),

  contrails: uniq([
    "Contrail_SprocketPoppy_Boat",
    "Trails_ID_123_TacticalWoodlandBlue",
    "Trails_ID_091_Longshorts",
    "Trails_ID_059_Sony2",
    "Trails_ID_019_PSBurnout",
  ]),

  lego: uniq([
    "JBPID_SOSO_Surface_Standard_M_02_A",
    "JBPID_SOSO_Light_Elec_Floor_03_B",
  ]),
};

const ALL_EXCLUSIVE_STYLES = [
  { cosmeticName: "Renegade Raider", styleText: "BLACK & GOLD", category: "skins" },
  { cosmeticName: "Aerial Assault Trooper", styleText: "BLACK & GOLD", category: "skins" },
  { cosmeticName: "Skull Trooper", styleText: "PURPLE GLOW", category: "skins" },
  { cosmeticName: "Ghoul Trooper", styleText: "PINK", category: "skins" },
  { cosmeticName: "The Paradigm", styleText: "REALITY WARRIOR", category: "skins" },
  { cosmeticName: "Aloy", styleText: "ICE HUNTER ALOY", category: "skins" },
  { cosmeticName: "Master Chief", styleText: "MATTE BLACK", category: "skins" },
  { cosmeticName: "Kratos", styleText: "ARMORED KRATOS", category: "skins" },
  { cosmeticName: "Marcus Fenix", styleText: "MARCUS FENIX (MATTE BLACK)", category: "skins" },
  { cosmeticName: "Fishstick", styleText: "WORLD CUP", category: "skins" },
  { cosmeticName: "Party Trooper", styleText: "J BALVIN", category: "skins" },
  { cosmeticName: "Party Trooper", styleText: "NEON PARTY TROOPER", category: "skins" },
  { cosmeticName: "Billie Eilish", styleText: "ULTRAVIOLET", category: "skins" },

  { cosmeticName: "Aerial Assault One", styleText: "BLACK & GOLD", category: "gliders" },

  { cosmeticName: "Raiders Revenge", styleText: "BLACK & GOLD", category: "pickaxes" },
  { cosmeticName: "Bow Blades", styleText: "CHROMATIC CARVERS", category: "pickaxes" },

  { cosmeticName: "Ghost Portal", styleText: "PURPLE", category: "backblings" },
];

function flattenAllExclusiveIds() {
  const out = new Set();

  for (const value of Object.values(ALL_EXCLUSIVE_ITEMS)) {
    for (const id of value) {
      out.add(normalizeId(id));
    }
  }

  return out;
}

module.exports = {
  ALL_EXCLUSIVE_ITEMS,
  ALL_EXCLUSIVE_STYLES,
  flattenAllExclusiveIds,
  normalizeId,
};